name = "ccr"
main = "index.ts"
compatibility_date = "2026-02-13"
routes = [
]

# Enable logging
[observability]
enabled = true
head_sampling_rate = 1


[vars]
OPENAI_BASE_URL = "https://openrouter.ai/api/v1"
